tab_about <- tabItem("about",
        box(title = "Summary", width = 12,
            #tags$div(
            HTML(paste(
                "This interactive dashboard is a companion to the paper <br>
                <b>Immune life-history, vaccination, and the dynamics of SARS-CoV-2 over the next five years</b>,<br>
                CM Saad-Roy*, CE Wagner*, RE Baker, SE Morris, J Farrar, AL Graham, SA Levin, MJ Mina, CJE Metcalf, BT Grenfell (*equal contribution), Science (2020).
                <br><br> <b> Abstract </b> <br>
                The future trajectory of the Covid-19 pandemic hinges on the dynamics of adaptive immunity against SARS-CoV2; 
                however, salient features of the immune response elicited by natural infection or vaccination are still uncertain.
                We use simple epidemiological models to explore estimates for the magnitude and timing of future Covid-19 cases given 
                different impacts of the adaptive immune response to SARS-CoV-2, as well as its interaction with vaccines and
                nonpharmaceutical interventions. We find that variations in the immune response to primary SARS-CoV-2 infections and a 
                potential vaccine can lead to dramatically different immunity landscapes and burdens of critically severe
                cases, ranging from sustained epidemics to near elimination. Our findings illustrate likely complexities in future Covid-19 dynamics, 
                and highlight the importance of immunological characterization beyond the measurement of active infections for adequately projecting 
                the immune landscape generated by SARS-CoV-2 infections.
                <br><br>
                The full paper can be found at <a href='https://science.sciencemag.org/content/early/2020/09/18/science.abd7343'>sciencemag.org</a>.<br><br><b>"
                ,
                tags$span("To use this dashboard, go to 'Interactive plots' on the sidebar, select one of the three models and 
                          choose desired parameters from the input options, then click 'Simulate model'.",
                          style="color:#EF4A4A"), sep = "") , "</b>",
                "<br><br>Details for all models can be found in the paper."
                )
            #)
        ),
        box(title = "SIR(S) model framework (no heterogeneity)", width = 12,
            tags$img(style="height:80%; width:80%", src="framework.png"),
            HTML("<br>Individuals can be fully susceptible (S<sub>P</sub>); undergoing primary infection (I<sub>P</sub>); 
                 naturally immune (R); susceptible to reinfection (S<sub>S</sub>) with reduced probability (&epsilon;); 
                 or undergoing secondary infection (I<sub>S</sub>) and transmitting with reduced probability (&alpha;).
                 Vaccine-induced immunity (V) is added as an additional and transient class 
                 (see the paper for full details). Also shown are frameworks for the limiting SIR and SIRS models 
                 (individuals are either fully susceptible (S), infected (I), or naturally immune (R)), and their representative time series.
                 Top row illustrations created at Biorender.com.")
    )
)
